version: 2.0
executorType: docker
containerInfo:
  - image: yarnpkg/dev:latest
stages:
  build:
    workDir: /home/ubuntu/project
    steps:
      - type: checkout

      - type: cache-restore
        key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - type: shell
        command: yarn install

      - type: shell
        name: Tests
        command: |
          node -v
          if [ "$CIRCLE_BRANCH" == 'master' ]; then
            ./scripts/set-dev-version.js
          fi;
          yarn lint
          yarn test-ci -- -- --maxWorkers 3
          yarn check-lockfile
          yarn build-dist
          node ./scripts/build-webpack.js
          ./scripts/build-deb.sh

      - type: cache-save
        key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths:
          - "~/.yarn-cache"

      - type: artifacts-store
        path: artifacts/
        destination: yarnpkg

deployment:
  release:
    tag: /v[0-9]+(\.[0-9]+)*/
    owner: yarnpkg
    commands:
      - ~/ghr/ghr -prerelease --username yarnpkg --repository yarn --token $KPM_CIRCLE_RELEASE_TOKEN v$(dist/bin/yarn --version) artifacts/
      - curl https://nightly.yarnpkg.com/sign_releases?token=$SIGN_TOKEN
      - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - ./scripts/set-installation-method.js "`pwd`/package.json" npm
      - npm publish --tag rc

notify:
  webhooks:
    - url: https://nightly.yarnpkg.com/api/archive_circleci
